### PR TITLE
test: validating JSON files

### LINKED ISSUE #78: Write tests to validate JSON files
All the data used to seed TechSchool comes from JSON files, and manually writing new courses on them is error-prone. Right now to avoid deploying incorrectly formatted JSON files, I run the `mix seed` script on my machine before to see if everything is working. But it would be nice to have some tests that check the formatting on the JSON files.

### PR DESCRIPTION
**Pull request by johnmcguin**
## Why is this change being made?
resolves #78

## How is this being accomplished?
1. A module to `use`, providing Ecto schemaless types for each JSON file
2. assert that each object in the file is a `valid?: true` Ecto changeset.

Some caveats I wanted to note:
- `cast`ing will not catch a typo like "names" instead of "name". It simply won't include those properties in the changes.
- You can perform required validations through the `required` argument when `use`ing the module. This is the main validation I included and consulted the schemas as to what fields should be required.
- If needed, you can override the `validate/1` function in a test file. For example, if you needed or wanted to perform additional validations on the changeset for that particular test file.

### CODE REVIEW

File: test/techschool/frameworks_json_test.ex [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+  setup_all do
+    {:ok, frameworks: get_json()}
+  end
+
+  describe "frameworks JSON validation" do
+    test "validates priv/repo/data/frameworks.json file", %{frameworks: frameworks} do
+      assert Enum.all?(frameworks, &valid/1)
+    end
+  end
```
Comment (danielbergholz) [inline test/techschool/frameworks_json_test.ex]: Looks very clean! I like this approach 🔥

**Review by danielbergholz — APPROVED** [review]
This is impressive work @johnmcguin, thanks a lot! Now I'm much more confident when adding any new data on the JSON files 🚀

**Comment by johnmcguin** [comment]
woohoo, thanks @danielbergholz ! Happy to find such a cool project to contribute to!
